### ISSUE TITLE
Build broken on OpenBSD

### ISSUE THREAD

**Issue by Pyrohh** [martanne/vis#60]
This was introduced in https://github.com/martanne/vis/commit/071b5f3c94c4b157a153586b087229f9e6b465d3, and is due to `stdin` already being defined in `stdio.h`

```
In file included from editor.c:6:
./editor.h:192:7: error: expected member name or ';' after declaration specifiers
        bool stdin;
        ~~~~ ^
/usr/include/stdio.h:206:16: note: expanded from macro 'stdin'
#define stdin   (&__sF[0])
                 ^
In file included from editor.c:6:
./editor.h:192:7: error: expected ')'
/usr/include/stdio.h:206:16: note: expanded from macro 'stdin'
#define stdin   (&__sF[0])
                 ^
./editor.h:192:7: note: to match this '('
/usr/include/stdio.h:206:15: note: expanded from macro 'stdin'
#define stdin   (&__sF[0])
                ^
```

I'm making an issue, as opposed to a pull request, because I don't know what to rename it to.
