### ISSUE TITLE
Does not build on OSX since 9915b9f 

### ISSUE THREAD

**Issue by erf** [martanne/vis#38]
Does not build on OSX since 9915b9f  on OSX  10.10.2

A couple of build errors:
./config.h:79:16: error: no member named 'statuswin' in 'struct EditorWin'
        wattrset(win->statuswin, focused ? A_REVERSE|A_BOLD : A_REVERSE);

In file included from vis.c:544:
./config.h:793:4: error: field designator 'statusbar' does not refer to any field in type 'Config'
                .statusbar = statusbar,

**Comment by twe4ked** [comment]
I got the same error. I needed to `rm config.h`. @martanne is this something you have to do before each build too? Or is it perhaps something to do the version of make that comes with OS X (GNU Make 3.81).

**Comment by Greduan** [comment]
Perhaps the config.h is outdated? When you delete config.h a default one (which is up-to-date) is used.

**Comment by erf** [comment]
I see. Deleting it works. Maybe there should be a warning for "outdated config.h". Or that it should be overwritten by the default config, and then you could config your own user config file.

**Comment by greduan** [comment]
I haven't seen any other program tell you there's an outdated config.h. It'd be much too complex a task.

Usually I just look at the diffs of the config.h if I run into any error and add any new options or update any changes.

**Comment by erf** [comment]
I agree, and i haven't really studied the code much, but if the default config file is lagging after new releases, then perhaps it should be overwritten and you'd have a empty 'user-config' file you could configure from scratch and keep up to date like with sublime and atom.

**Comment by matiaslina** [comment]
> It'd be much too complex a task, for what it's worth.

Not really. A hash on the top of the config.def.h would do the trick. just compare the hash on the top of config.def.h with the hash on top of config.h. 

But yeah, doing a diff and updating the config.h it's the best solution now.

**Comment by greduan** [comment]
yeah but the user config.h will be different from config.def.h, so automatically the hashes would be different. So really the program would have to run a full diff of the files and understand what was added with each commit and understand what's a user change etc. It's just not worth it to add this, from a dev's perspective.

Much easier for a human to read and check before compiling. :)

**Comment by erf** [comment]
is it not possible for config.def.h to include an initially empty config.h which could extend the default settings?

**Comment by erf** [comment]
im no c man, but i guess the static c code is difficult to expand on by for example having a default config file including a user config or something, and i guess there are no plans on making this more configurable using parsed text files.. ?

**Comment by matiaslina** [comment]
@greduan: I'm saying to add a hash on the top of the config.def.h as a comment, so we can check with something like 
```bash
if [ "$(head -n 1 config.def.h)" != "$(head -n 1 config.h)" ]
then
     echo "outdated config.h"
fi
```
Anyhow, it's just an alert. You manually have to do the diff and merge the files.

> is it not possible for config.def.h to include an initially empty config.h which could extend the default settings?

No that I know (never tried.). You can run `ln -s config.def.h config.h` and do your changes on the config.def.h, commit them, and on a git pull they should merge automatically.

**Comment by greduan** [comment]
@matiaslina ah I see. That's actually not a bad idea.

**Comment by martanne** [comment]
From my point of view, the real problem is that `config.def.h` currently contains way too much implementation details.
