### ISSUE TITLE
Can't compile with Lua 5.4 on OpenBSD

### ISSUE THREAD

**Issue by aletschfirn** [martanne/vis#1401]
### Problem

```
make
cc -Wall -pipe -Wno-initializer-overrides -Wno-override-init -O2 -ffunction-sections -fdata-sections -fPIE -fstack-protector-all -DTERMINFO='"/usr/share/terminfo"' -DTERMINFO_DIRS='"/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/usr/local/share/terminfo:/usr/local/lib/terminfo"' -DCONFIG_CURSES=1    -I/usr/local/include -DCONFIG_TRE=1 -I/usr/local/include/lua-5.4 -DCONFIG_LUA=1  -std=c99 -DNDEBUG -D_BSD_SOURCE -DVERSION=\"\" -DVIS_API=  -DVIS_EXPORT=static -DVIS_PATH=\"/usr/local/share/vis\"  main.c -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -lncursesw    -L/usr/local/lib -ltre -L/usr/local/lib -llua5.4 -lm  -lc  -o vis
In file included from main.c:2:
In file included from ./vis.c:19:
./vis-lua.c:3392:28: error: expected expression
 3392 |         lua_pushinteger(L, VIS_API);
      |                                   ^
1 error generated.
*** Error 1 in /home/ahkka/Projects/vis (Makefile:39 'vis')
```

and ./configure outputs:
```
./configure
checking for C compiler... cc
checking whether C compiler works... yes
checking whether compiler accepts -Werror=unknown-warning-option... yes
checking whether compiler accepts -Werror=unused-command-line-argument... yes
checking whether linker accepts -Werror=unknown-warning-option... yes
checking whether linker accepts -Werror=unused-command-line-argument... yes
checking whether compiler accepts -Wall... yes
checking whether compiler accepts -pipe... yes
checking whether compiler accepts -Wno-initializer-overrides... yes
checking whether compiler accepts -Wno-override-init... yes
checking whether compiler accepts -O2... yes
checking whether compiler accepts -ffunction-sections... yes
checking whether compiler accepts -fdata-sections... yes
checking whether linker accepts -Wl,--gc-sections... yes
checking whether compiler accepts -fPIE... yes
checking whether compiler accepts -fstack-protector-all... yes
checking whether linker accepts -Wl,-z,now... yes
checking whether linker accepts -Wl,-z,relro... yes
checking whether linker accepts -pie... no
creating config.mk... done
checking for pkg-config... yes
checking for libcurses...
 checking for ncursesw... yes
checking for libtre... yes
checking for liblua >= 5.2 ...
 checking for lua... no
 checking for lua5.5... no
 checking for lua5.4... yes
checking for Lua statically linked liblpeg...
 checking for static lpeg... no
 checking for static lua5.5-lpeg... no
 checking for static lua5.4-lpeg... no
 checking for static lua5.3-lpeg... no
 checking for static lua5.2-lpeg... no
completing config.mk... done
```

also lpeg isn't found but whatever, happens

same also happens with gcc:
```
ryolaptop$ CC=egcc ./configure
checking for C compiler... egcc
checking whether C compiler works... yes
checking whether compiler accepts -Werror=unknown-warning-option... no
checking whether compiler accepts -Werror=unused-command-line-argument... no
checking whether linker accepts -Werror=unknown-warning-option... no
checking whether linker accepts -Werror=unused-command-line-argument... no
checking whether compiler accepts -Wall... yes
checking whether compiler accepts -pipe... yes
checking whether compiler accepts -Wno-initializer-overrides... no
checking whether compiler accepts -Wno-override-init... yes
checking whether compiler accepts -O2... yes
checking whether compiler accepts -ffunction-sections... yes
checking whether compiler accepts -fdata-sections... yes
checking whether linker accepts -Wl,--gc-sections... yes
checking whether compiler accepts -fPIE... yes
checking whether compiler accepts -fstack-protector-all... yes
checking whether linker accepts -Wl,-z,now... yes
checking whether linker accepts -Wl,-z,relro... yes
checking whether linker accepts -pie... yes
creating config.mk... done
checking for pkg-config... yes
checking for libcurses...
 checking for ncursesw... yes
checking for libtre... yes
checking for liblua >= 5.2 ...
 checking for lua... no
 checking for lua5.5... no
 checking for lua5.4... yes
checking for Lua statically linked liblpeg...
 checking for static lpeg... no
 checking for static lua5.5-lpeg... no
 checking for static lua5.4-lpeg... no
 checking for static lua5.3-lpeg... no
 checking for static lua5.2-lpeg... no
completing config.mk... done
ryolaptop$ make
egcc -Wall -pipe -Wno-override-init -O2 -ffunction-sections -fdata-sections -fPIE -fstack-protector-all -DTERMINFO='"/usr/share/terminfo"' -DTERMINFO_DIRS='"/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/usr/local/share/terminfo:/usr/local/lib/terminfo"' -DCONFIG_CURSES=1    -I/usr/local/include -DCONFIG_TRE=1 -I/usr/local/include/lua-5.4 -DCONFIG_LUA=1  -std=c99 -DNDEBUG -D_BSD_SOURCE -DVERSION=\"\" -DVIS_API=  -DVIS_EXPORT=static -DVIS_PATH=\"/usr/local/share/vis\"  main.c -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -pie -lncursesw    -L/usr/local/lib -ltre -L/usr/local/lib -llua5.4 -lm  -lc  -o vis
In file included from vis.c:19,
                 from main.c:2:
vis-lua.c: In function 'vis_lua_init':
vis-lua.c:3392:35: error: expected expression before ')' token
 3392 |         lua_pushinteger(L, VIS_API);
      |                                   ^
*** Error 1 in /home/ahkka/Projects/vis (Makefile:39 'vis')
```

lua 5.4 comes from official repos if that matters

### vis version (vis -v)

Commit 254329d9f4f1df1158397080d403f3f112918aff

**Comment by aletschfirn** [comment]
Checked pull requests, it actually falls under https://github.com/martanne/vis/pull/1384 with fix there. Wish it'll get noticed soon

**Comment by aletschfirn** [comment]
The other issue that I got is that plugins that use API to handle styling from pull 1180 doesn't work and both vis-paw and vis-modal fails to load. Unsure if it is specific to OpenBSD or not but it is there

**Comment by aletschfirn** [comment]
The issue with styling is fixed by building statically
